id = "haproxy-dev"
name = "HAProxy"
version = "0.1.0"
schema_version = 1
authors = ["Brandon Froehlich <bfroehlich@ferrilli.com>"]
description = "HAProxy configuration file syntax highlighting"

[grammars.haproxy]
path = "tree-sitter-haproxy.wasm"
